CREATE FUNCTION calc_add(int,int ) RETURNS INT as 'MODULE_PATHNAME','calc_add' LANGUAGE C STRICT;
CREATE FUNCTION calc_sub(int,int ) RETURNS INT as 'MODULE_PATHNAME','calc_sub' LANGUAGE C STRICT;
CREATE FUNCTION calc_mul(int,int ) RETURNS INT as 'MODULE_PATHNAME','calc_mul' LANGUAGE C STRICT;
CREATE FUNCTION calc_div(int,int ) RETURNS INT as 'MODULE_PATHNAME','calc_div' LANGUAGE C STRICT;
CREATE FUNCTION calc_mod(int,int ) RETURNS INT as 'MODULE_PATHNAME','calc_mod' LANGUAGE C STRICT;
CREATE FUNCTION calc_pow(int,int ) RETURNS INT as 'MODULE_PATHNAME', 'calc_pow' LANGUAGE C STRICT;
